### ISSUE TITLE
morphMany exception in Commentable model

### ISSUE THREAD

**Issue by hexhov** [RomainLanz/laravel-commentable#1]
Hello, nice work based on good principle of nested set. But after installing following the instruction in Laravel 4.2 I get an exception contains:

Missing argument 2 for Illuminate\Database\Eloquent\Model::morphMany(), called in "_ROOT_/vendor/lanz/laravel-commentable/src/Commentable/Commentable.php" on line 13 and defined.

After editing this file and replacing return string by following code:  

return $this->morphMany('Lanz\Commentable\Comment', 'commentable');

all works fine, but what is this bug or feature? Am I missed something?

**Comment by RomainLanz** [comment]
Hey @hexhov,

Good catch!

This is corrected in the 1.0.1 release.
Thanks for your feedback.
