### ISSUE TITLE
Demo / Example

### ISSUE THREAD

**Issue by illuminate3** [RomainLanz/laravel-commentable#10]
How are you showing the returned comments?

thanks!

**Comment by askaoru** [comment]
A simple  example for returning comments on user profile

````
// Controller on show method

public function show($id)
	{	
		$user = User::find($id);
	        $comments = $user->comments()->orderBy('created_at', 'DESC')->paginate(10);

		return view('user.view', compact('user','comments'));
	}
````

````
// On your view file

@foreach($comments as $comment)
    {{ $comment->user_id }} // will return the user_id of the commentor 
    {{ $comment->title }} // will return the comment title
    {{ $comment->body }} // will return the body of the comment
    {{ $comment->created_at->diffForHumans() }} // WIll return created at in 'x seconds ago' format
@endforeach
````

Style them as you see fit. and use relationship to fetch more items related to the comment

**Comment by illuminate3** [comment]
Awesome!

Thanks

**Comment by illuminate3** [comment]
Where you able to use a presenter() for the user_id?
I'm getting Baum errors ...

**Comment by RomainLanz** [comment]
Dear @illuminate3, @askaoru,

Sorry for the delay, I'm completely busy and I can't give you an answer for the moment...
I hope that someone will help you.

Try to ask this question in the Baum repository (https://github.com/etrepat/baum).

**Comment by RomainLanz** [comment]
@illuminate3,

Did you find a solution? Which error do you get?

**Comment by RomainLanz** [comment]
There is an [example repository](https://github.com/Slynova-Org/laravel-commentable-example) with the [new version of the package](https://github.com/Slynova-Org/laravel-commentable).

Please, ask your question there.
