### ISSUE TITLE
Threaded Comments: how does it work?

### ISSUE THREAD

**Issue by Halnex** [RomainLanz/laravel-commentable#11]
Can you give us an example of how would threaded comments work?

**Comment by RomainLanz** [comment]
Dear @Halnex,

Sorry for the delay, I'm completely busy for the moment and I can't give you an answer for the moment...
I hope that someone will help you.

**Comment by huglester** [comment]
It is probably something like this:

You find comments with ID: 3.

Later it returns a tree, with for example comment1, and someone who replied with comment2 to comment1, and someone who replied with comment3 to comment2.
@RomainLanz probably wants HTML example?

**Comment by huglester** [comment]
@Halnex did you solve your problem?

as for now my all comments are saved with NULL values for parent_id, lft, rgt, depth

**Comment by huglester** [comment]
@RomainLanz sorry for disturbing you. But maybe you have at least some dummy example on how to create childs and list the comments?

So far (in theory) somethine like this should work: 

```php
$item = News::first();

// we find comment, we want to replyTo:
$parent = Comment::findOrFail(11);

// attach the comment as child of id:11, and bind to 'News' model:
$new_comment = new Comment($input);
$new_comment->makeChildOf($parent);
$item->comments()->create($new_comment);

```

But this does not work, I get: ErrorException [ Recoverable Error ]: Argument 1 passed to Baum\Move::setEventDispatcher() must be an instance of Illuminate\Events\Dispatcher, null given, called in /--/vendor/baum/baum/src/Baum/Move.php on line 73 and defined

Any ideas?

**Comment by RomainLanz** [comment]
Dear @Halnex, @huglester,

I'm writing a new version of this package at this moment.
I have some examples (I'll create a example repository to create and list comments).

Here's what you need, note that morph fields (`commentable_id` and `commentable_type`) need to be nullable.
```php
// Expect that we have an article..
$article1 = Article::create(['id' => 1, 'title' => 'Laravel Commentable, new version !', 'body' => 'First post.']);

// and some users...
$user1= User::create(['id' => 1, 'name' => 'John Doe', 'email' => 'john@example.com', 'password' => 'secret']);
$user2 =User::create(['id' => 2, 'name' => 'Jane Doe', 'email' => 'jane@example.com', 'password' => 'secret']);

// I write a first comment to the article
$comment1 = $article1->comments()->create(['body' => 'Super article!', 'user_id' => $user1->id]);

//then a second user answered this comment
$comment2 = Comment::create(['body' => "No, it's a really bad article!", 'user_id' => $user2->id]);
$comment2->makeChildOf($comment1);

// and the first user reply
$comment3 = Comment::create(['body' => "You'r damn crazy girl!", 'user_id' => $user1->id]);
$comment3->makeChildOf($comment2);

// then the second user write a comment
$comment4 = $article1->comments()->create(['body' => "That's a very bad post, only shit in it", 'user_id' => $user2->id]);
```

To display comments you need to do some recursive stuff (depends on the number of level you have)
```html
{-- Shitty quickly written code --}
@foreach ($article->comments as $comment)
  <div class="comment">
    <p>{{ $comment->body }} <small>by {{ $comment->user->name }}</small></p>

    @if ($comment->hasChildren())
      @foreach ($comment->getImmediateDescendants() as $child)
        <b>{{ $child->body }} <small>by {{ $child->user->name }}</small></b><br>

        @if ($child->hasChildren())
          @foreach ($child->getImmediateDescendants() as $childchild)
            <b><i>{{ $childchild->body }} <small>by {{ $childchild->user->name }}</small></i></b><br>
          @endforeach
        @endif
      @endforeach
    @endif
  </div>
  <hr>
@endforeach
```

Does it help ?

**Comment by RomainLanz** [comment]
@Halnex, @huglester 

https://github.com/Slynova-Org/laravel-commentable

**Comment by huglester** [comment]
@RomainLanz hello, thanks for these examples and new repo with a fresh version. I will play with it tommorow and see how it goes. 

As I see this repo is abandoned on packagist already - but I post back here or to the new repo tommorow!

Thank you

**Comment by RomainLanz** [comment]
If you have some question I recommend you to post in the [example repository](https://github.com/Slynova-Org/laravel-commentable-example).

**Comment by huglester** [comment]
@RomainLanz I get this: Baum\MoveNotPossibleException [ 0 ]: A node cannot be moved to a descendant of itself (inside moved tree).

Note, I am using this package outside laravel. Maybe you have some ideas what I can be doing wrong?

**Comment by RomainLanz** [comment]
Can I see your code?

**Comment by huglester** [comment]
It is basicly the one you posted :(

```php
$article1 = Naujienos_m::active()
            ->where('slug', $slug)
            ->first();


// this one works (`comment1` is stored)
        $comment1 = $article1->comments()->create(['body' => 'Super article!']);

// this one works - `comment2` is created
        $comment2 = Comment::create(['body' => "No, it's a really bad article!"]);


// this one gives the error above:
        $comment2->makeChildOf($comment1);
```

**Comment by RomainLanz** [comment]
Did you have change the migration?

https://github.com/Slynova-Org/laravel-commentable/blob/1.0/src/migrations/2015_11_06_000000_create_comments_table.php

**Comment by huglester** [comment]
One thing I have changed is nu add:
unsigned() to:
parent_id, lft, rgt, depth.

But I now tried reverting the changer, re-migrate the DB - but same results

**Comment by huglester** [comment]
Even such a simple scenario fails here:

```php
        $c1 = Comment::firstOrCreate(['body' => 'Comment 1']);
        $c2 = Comment::firstOrCreate(['body' => 'Comment 2']);

        $c2->makeChildOf($c1);
```

This must be somewhere in Baum package, or I am missing something?

**Comment by RomainLanz** [comment]
Can you take another screenshot of phpmyadmin after running 

```php
// Expect that we have an article..
$article1 = Article::create(['id' => 1, 'title' => 'Laravel Commentable, new version !', 'body' => 'First post.']);

// and some users...
$user1 = User::create(['id' => 1, 'name' => 'John Doe', 'email' => 'john@example.com', 'password' => 'secret']);
$user2 = User::create(['id' => 2, 'name' => 'Jane Doe', 'email' => 'jane@example.com', 'password' => 'secret']);

// A user writes a first comment to the article
$comment1 = $article1->comments()->create(['body' => 'Super article!', 'user_id' => $user1->id]);

// then a second user answered this comment
$comment2 = Comment::create(['body' => "No, it's a really bad article!", 'user_id' => $user2->id]);
$comment2->makeChildOf($comment1);

// and the first user reply
$comment3 = Comment::create(['body' => "You'r damn crazy girl!", 'user_id' => $user1->id]);
$comment3->makeChildOf($comment2);

// then the second user write a comment
$comment4 = $article1->comments()->create(['body' => "That's a very bad post, only bad advices", 'user_id' => $user2->id]);
```

**Comment by huglester** [comment]
Hello @RomainLanz , sorry for a delay!

Here is the screenshot: http://pic.webas.lt/webas.lt-02dbd3786b.png
Only 2nd comment gets created, later I get the exception when creating a child :(

If that works at your side, I wonder what is happening under the hood that it does not work ourside laravel?

**Comment by RomainLanz** [comment]
When you say that you're not using Laravel what does that mean?

**Comment by huglester** [comment]
Well it means I am just requiring yoru package. and using it in CodeIgniter tree. TOgether with installed eloquent, dispatcher packages, etc.

Eloquent oparations work without problems, events work also. But this stuff is not :( 

I will take fresh L5 install, and try to make similar scenario to see if it at least works there!

**Comment by huglester** [comment]
I tried your package together with laravel. and it works ...

Then I am not sure what so strange is hapening when I try craete comments outside of laravel :(

**Comment by RomainLanz** [comment]
I can't help you for that :( Never use CodeIgniter.

**Comment by huglester** [comment]
Hello,

Since I am using this package outside the Laravel, I have registered Eloquent wrong.

I missed this step: `$capsule->setEventDispatcher(new Dispatcher(new Container));`

Full connection code:
```php
                        $capsule = new Capsule;
			$capsule->addConnection([
				'driver'    => 'mysql',
				'host'      => 'localhost',
				'database'  => 'test',
				'username'  => 'homestead',
				'password'  => 'secret',
				'charset'   => 'utf8',
				'collation' => 'utf8_unicode_ci',
				'prefix'    => '',
			]);
			$capsule->setEventDispatcher(new Dispatcher(new Container));
			$capsule->setAsGlobal();
			$capsule->bootEloquent();
```

now it works :)

thanks

**Comment by RomainLanz** [comment]
Aaaah, very nice to read that it works for you.
