### ISSUE TITLE
With laravel 5.2: Call to undefined method Illuminate\Foundation\Application::bindShared()

### ISSUE THREAD

**Issue by the-foreigner** [RomainLanz/laravel-commentable#13]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Foundation\Application::bindShared()

Potential fix:
https://github.com/laracasts/flash/commit/6c435061482a513220ed4ee48b498f4453207c9e

**Comment by RomainLanz** [comment]
This package is not maintained anymore.

https://github.com/Slynova-Org/laravel-commentable
