### ISSUE TITLE
L 5.2 compatibility

### ISSUE THREAD

**Issue by UnrulyNatives** [RomainLanz/laravel-commentable#16]
Error when creating migrations:
`Fatal Throwable Error in Commentable ServiceProvider.php line 20: Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared()`

## Solution: 
`bindShared` has been renamed to `singleton`

https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-illuminatefoundationapplicationbindshared

In `D:\www\!Kailong\vendor\lanz\laravel-commentable\src\Commentable\CommentableServiceProvider.php`

line 20 you should change

        $this->app->bindShared('command.commentable.migration', function ($app) {
            return new MigrationCommand();

to 

        $this->app->singleton('command.commentable.migration', function ($app) {
            return new MigrationCommand();

**Comment by RomainLanz** [comment]
This package is not maintained anymore.

Please read https://github.com/RomainLanz/laravel-commentable/pull/14

Thanks.
