### ISSUE TITLE
 Class 'Baum\BaumServiceProvider' not found

### ISSUE THREAD

**Issue by hardikaecor** [RomainLanz/laravel-commentable#2]
Hi after installing I got following error
 Class 'Baum\BaumServiceProvider' not found
I have checked the code for Baum and they have changed the namespace
Should i keep the pull request for the change?

**Comment by RomainLanz** [comment]
Hey @hardikaecor,

Thanks for your feedback.
Change are done. You need to update to the release 2.0.2.

**Comment by hardikaecor** [comment]
Thanks very much  for instant fix :)
