### ISSUE TITLE
a small foreign key constraint problem

### ISSUE THREAD

**Issue by UnrulyNatives** [RomainLanz/laravel-commentable#3]
I just installed a fresh  copy of Laravel and your package.
Migration went OK, but when I try to get the first comment, I got

    QueryException in Connection.php line 620:
    SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`langri_wisdom2`.`comments`, CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)) (SQL: insert into `comments` (`body`, `commentable_type`, `commentable_id`, `lft`, `rgt`, `updated_at`, `created_at`) values (My first comment!, quotation, 112, 7, 8, 2015-03-23 09:57:12, 2015-03-23 09:57:12))

The user_id written to database is 0 and I need to manually disable the foreign key constraint to have the first comment written to the database.

My solution: 

I added into the code this line to get the job done: 

    $comment->user_id = Auth::id();

I suggest you improve the readmen.md file for others.

Thank you for your ackage,

Peter

**Comment by RomainLanz** [comment]
Mmmh, you're right. I'll change it to specify the user_id.

Thanks !
