### ISSUE TITLE
another minor issue

### ISSUE THREAD

**Issue by UnrulyNatives** [RomainLanz/laravel-commentable#4]
In my User model I have a function to display Gravatar

    public function getGravatarAttribute()
    {
    $hash = md5(strtolower(trim($this->attributes['email'])));
    return "http://www.gravatar.com/avatar/$hash";
    }

In order to make it work I had to declare class (damn the L5 for this)
in the file
vendor\lanz\laravel-commentable\src\Commentable\Comment.php
    
    use Config;

You might want to modify the file for the benefit of others.

Thx.

**Comment by RomainLanz** [comment]
I didn't understand why you want to use `Config` in `Comment`. But if you need to change `Comment` class you need to create a `Comment` model and extend my class.

**Comment by UnrulyNatives** [comment]
I have never extended a Class before - sorry, I am an amateur programmer. I will try to do it.

When I used your packege out-of-the-box, I just got the missing class error. In the file I have pointed in my initial post you have this function:

    public function user()
    {
        return $this->belongsTo(Config::get('auth.model'));
    }

I use it when I want to print gravatar in my VIEW file:

    {{ $o->user->gravatar }}

And you need to add a backslash before Config:: or declare the class in the head of the file.
That's what I had to do to make the thing work.

**Comment by RomainLanz** [comment]
Oooh, you're right again!

I've just commited, let me create a new tag.

**Comment by RomainLanz** [comment]
Let me know if it's ok with the new release.

**Comment by UnrulyNatives** [comment]
I will install your package on a new app tomorrow and will let you know.


Thx again.

**Comment by UnrulyNatives** [comment]
The new release works perfectly!

**Comment by RomainLanz** [comment]
:+1:
