### ISSUE TITLE
Migration foreign key constraint

### ISSUE THREAD

**Issue by hooligan** [RomainLanz/laravel-commentable#6]
I had trouble with the migrations script complaining about the foreign key constraint on the migration.

[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `comme
  nts` add constraint comments_user_id_foreign foreign key (`user_id`) references `users` (`id`))

I updated 

$table->integer('user_id');

To

$table->integer('user_id')->unsigned();

Which matches the column in the users table.

**Comment by RomainLanz** [comment]
Hey @hooligan,

Thanks for your feedback and sorry for the delay.
This is corrected on the latest release: https://github.com/RomainLanz/laravel-commentable/releases/tag/v1.0.4
