### ISSUE TITLE
Can't generate migration on Laravel 5.1

### ISSUE THREAD

**Issue by Hukuta** [RomainLanz/laravel-commentable#7]
php artisan commentable:migration

> Tables: comments
> A migration that creates "comments" tables will be created in app/database/migrations directory

> Process finished with exit code 0 at 15:29:01.
> Execution time: 191 ms.

     php artisan migrate
> Nothing to migrate.

> Process finished with exit code 0 at 15:30:17.
> Execution time: 218 ms.

migration is not created - no any new files
but if a try this:

     php artisan make:model Comment --migration
>Model created successfully.
>Created Migration: 2015_07_29_123328_create_comments_table

>Process finished with exit code 0 at 15:33:28.
>Execution time: 224 ms.

file 2015_07_29_123328_create_comments_table is created

**Comment by RomainLanz** [comment]
Hi @Hukuta,

As a workaround you could copy/paste the content of my migration (https://github.com/RomainLanz/laravel-commentable/blob/2.0/src/migrations/create_comments_table.php).

Thanks for the report, I will investigate and maybe use the default publishing system.

**Comment by RomainLanz** [comment]
I'll update to use the default system to create migration.

Thanks for your report.
