### ISSUE TITLE
php artisan migrate:rollback

### ISSUE THREAD

**Issue by rstrst** [RomainLanz/laravel-commentable#8]
[Symfony\Component\Debug\Exception\FatalErrorException]  
Class 'CreateCommentsTable' not found

**Comment by RomainLanz** [comment]
Dear @rstrst,

Can I have more information?

**Comment by rstrst** [comment]
I'am getting this error when trying to rollback migration.


Looks like this is same issue as previous, i fix it with creating own migration.

Thanks for your package.

**Comment by RomainLanz** [comment]
I'll update to use the default system to create migration.

Thanks for your report.
