### ISSUE TITLE
Paginating the comments?

### ISSUE THREAD

**Issue by guyyosan** [RomainLanz/laravel-commentable#9]
Hi,
How can I go about paginating the comments?
I tired both $post->comments->paginate(10)
$post->comments()->paginate(10)
and tried adding a getAttribute to the comments triat didn't work, any suggestion?

**Comment by RomainLanz** [comment]
Dear @guyyosan,

Sorry for the delay, which error do you get?

**Comment by RomainLanz** [comment]
There is an [example repository](https://github.com/Slynova-Org/laravel-commentable-example) with the [new version of the package](https://github.com/Slynova-Org/laravel-commentable).

Please, ask your question there.
